######################################################################
# Automatically generated by qmake (3.0) ? 3? 18 22:31:19 2016
######################################################################

TEMPLATE = app
TARGET = Daruin
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets
