######################################################################
# Automatically generated by qmake (3.0) ? 3? 21 17:43:15 2016
######################################################################

TEMPLATE = app
TARGET = Daruin
INCLUDEPATH += .

# Input
HEADERS += Daruin.h
SOURCES += Daruin.cpp main.cpp
QT += widgets
